# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sdp}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 1.3.6") if s.respond_to? :required_rubygems_version=
  s.authors = ["sloveless"]
  s.date = %q{2011-01-22}
  s.description = %q{This gem allows for parsing SDP (Session Description Protocol) information in to a Ruby object, making it easy to read and work with that data.  It also allows for easily creating SDP objects that can be converted to text using #to_s.}
  s.email = %q{steve.loveless@gmail.com}
  s.extra_rdoc_files = [
    "ChangeLog.rdoc",
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".infinity_test",
    ".rspec",
    ".yardopts",
    "ChangeLog.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "features/sdp_create.feature",
    "features/sdp_get.feature",
    "features/step_definitions/sdp_create_steps.rb",
    "features/step_definitions/sdp_get_steps.rb",
    "features/support/env.rb",
    "features/support/sdp_file.txt",
    "gemspec.yml",
    "lib/sdp.rb",
    "lib/sdp/description.rb",
    "lib/sdp/parser.rb",
    "lib/sdp/session_template.erb",
    "lib/sdp/version.rb",
    "sdp.gemspec",
    "spec/sdp/description_spec.rb",
    "spec/sdp/parser_spec.rb",
    "spec/sdp_spec.rb",
    "spec/spec_helper.rb",
    "tasks/metrics.rake",
    "tasks/roodi_config.yml",
    "tasks/stats.rake"
  ]
  s.has_rdoc = %q{yard}
  s.homepage = %q{http://rubygems.org/gems/sdp}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{sdp}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Parse and create SDP (Session Description Protocol) text based on RFC4566.}
  s.test_files = [
    "spec/sdp/description_spec.rb",
    "spec/sdp/parser_spec.rb",
    "spec/sdp_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<parslet>, ["~> 1.0.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_runtime_dependency(%q<parslet>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_development_dependency(%q<ore-core>, ["~> 0.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.0"])
      s.add_development_dependency(%q<ore-tasks>, ["~> 0.3.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<infinity_test>, [">= 0"])
      s.add_development_dependency(%q<metric_fu>, [">= 0"])
      s.add_development_dependency(%q<code_statistics>, ["~> 0.2.13"])
    else
      s.add_dependency(%q<parslet>, ["~> 1.0.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<parslet>, ["~> 1.0.0"])
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<ore-core>, ["~> 0.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.0"])
      s.add_dependency(%q<ore-tasks>, ["~> 0.3.0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<infinity_test>, [">= 0"])
      s.add_dependency(%q<metric_fu>, [">= 0"])
      s.add_dependency(%q<code_statistics>, ["~> 0.2.13"])
    end
  else
    s.add_dependency(%q<parslet>, ["~> 1.0.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<parslet>, ["~> 1.0.0"])
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<ore-core>, ["~> 0.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.0"])
    s.add_dependency(%q<ore-tasks>, ["~> 0.3.0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<infinity_test>, [">= 0"])
    s.add_dependency(%q<metric_fu>, [">= 0"])
    s.add_dependency(%q<code_statistics>, ["~> 0.2.13"])
  end
end

